Persist vital directories to disk on nodes Directories include: - $HOME - /etc/kubernetes (for checkpointer manifests and kubeconfig) - /var/etcd (for etcd-operator initiated etcd pods) - /var/lib/{docker,rkt} (store images to disk)
Uses btrfs.

diff --git a/templates/node.yaml b/templates/node.yaml
--- a/templates/node.yaml
+++ b/templates/node.yaml
@@ -40,26 +40,19 @@ systemd:
         ExecStart=/bin/sh -c 'while ! /usr/bin/grep '^[^#[:space:]]' /etc/resolv.conf > /dev/null; do sleep 1; done'
         [Install]
         RequiredBy=kubelet.service
-        RequiredBy=srv-images.mount
-        RequiredBy=var-lib-docker.mount
-        RequiredBy=var-lib-rkt.mount
-        RequiredBy=etc-kubernetes.mount
-        RequiredBy=var-lib-rook.mount
-        RequiredBy=var-etcd.mount
     - name: kubelet.path
       enable: true
       contents: |
         [Unit]
         Description=Watch for kubeconfig
         [Path]
-        PathExists=/etc/kubernetes/kubeconfig
+        PathExists=/etc/kubeconfig
         [Install]
         WantedBy=multi-user.target
     - name: kubelet.service
       contents: |
         [Unit]
         Description=Kubelet via Hyperkube ACI
-        RequiresMountsFor=/var/lib/rook
         [Service]
         EnvironmentFile=/etc/kubelet.env
         Environment="RKT_RUN_ARGS=--uuid-file-save=/var/run/kubelet-pod.uuid \
@@ -107,22 +100,270 @@ systemd:
         WorkingDirectory=/opt/bootkube
         ExecStart=/opt/bootkube/bootkube-start
         ExecStartPost=/bin/touch /opt/bootkube/init_bootkube.done
+    - name: DATA.mount
+      enable: true
+      contents: |
+        [Unit]
+        ConditionPathIsSymbolicLink=/dev/disk/by-label/DATA
+
+        [Mount]
+        What=/dev/disk/by-label/DATA
+        Where=/DATA
+        Type=btrfs
+        Options=compress=lzo,subvol=/
+
+        [Install]
+        WantedBy=local-fs.target
+    - name: DATA.automount
+      enable: true
+      contents: |
+        [Automount]
+        Where=/DATA
+
+        [Install]
+        WantedBy=local-fs.target
+    - name: btrfs-create-subvolumes.service
+      enable: true
+      contents: |
+        [Unit]
+        Description=Initial BTRFS subvolume creation
+        RequiresMountsFor=/DATA
+        ConditionDirectoryNotEmpty=!/DATA
+
+        [Service]
+        Type=oneshot
+        RemainAfterExit=true
+        ExecStart=/usr/sbin/btrfs subvolume create /DATA/docker
+        ExecStart=/usr/sbin/btrfs subvolume create /DATA/rkt
+        ExecStart=/usr/sbin/btrfs subvolume create /DATA/etcd
+        ExecStart=/usr/sbin/btrfs subvolume create /DATA/kubernetes
+        ExecStart=/usr/sbin/btrfs subvolume create /DATA/core
+        ExecStart=/usr/sbin/btrfs subvolume create /DATA/kubelet
+        ExecStart=/usr/bin/chown -R core:core /DATA/core
+
+        [Install]
+        WantedBy=multi-user.target
+    - name: var-lib-docker.mount
+      enable: true
+      contents: |
+        [Unit]
+        Before=docker.service
+
+        [Mount]
+        What=/dev/disk/by-label/DATA
+        Where=/var/lib/docker
+        Type=btrfs
+        Options=compress=lzo,subvol=/docker
+    - name: var-lib-docker.automount
+      enable: true
+      contents: |
+        [Unit]
+        Requires=DATA.mount
+        Wants=btrfs-create-subvolumes.service
+        After=DATA.mount
+        After=btrfs-create-subvolumes.service
+        Before=docker.service
+
+        [Automount]
+        Where=/var/lib/docker
+
+        [Install]
+        WantedBy=docker.service
+        WantedBy=local-fs.target
+    - name: var-lib-rkt.mount
+      enable: true
+      contents: |
+        [Unit]
+        Before=rkt-gc.service rkt-metadata.service
+
+        [Mount]
+        What=/dev/disk/by-label/DATA
+        Where=/var/lib/rkt
+        Type=btrfs
+        Options=compress=lzo,subvol=/rkt
+    - name: var-lib-rkt.automount
+      enable: true
+      contents: |
+        [Unit]
+        Requires=DATA.mount
+        Wants=btrfs-create-subvolumes.service
+        After=DATA.mount
+        After=btrfs-create-subvolumes.service
+        Before=rkt-gc.service rkt-metadata.service
+
+        [Automount]
+        Where=/var/lib/rkt
+
+        [Install]
+        WantedBy=rkt-gc.service rkt-metadata.service
+        WantedBy=local-fs.target
+    - name: var-lib-kubelet.mount
+      enable: true
+      contents: |
+        [Unit]
+        Before=kubelet.service
+
+        [Mount]
+        What=/dev/disk/by-label/DATA
+        Where=/var/lib/kubelet
+        Type=btrfs
+        Options=compress=lzo,subvol=/kubelet
+    - name: var-lib-kubelet.automount
+      enable: true
+      contents: |
+        [Unit]
+        Requires=DATA.mount
+        Wants=btrfs-create-subvolumes.service
+        After=DATA.mount
+        After=btrfs-create-subvolumes.service
+        Before=kubelet.service
+
+        [Automount]
+        Where=/var/lib/kubelet
+
+        [Install]
+        WantedBy=local-fs.target
+        WantedBy=kubelet.service
+    - name: var-etcd.mount
+      enable: true
+      contents: |
+        [Unit]
+        Before=kubelet.service
+
+        [Mount]
+        What=/dev/disk/by-label/DATA
+        Where=/var/etcd
+        Type=btrfs
+        Options=compress=lzo,subvol=/etcd
+    - name: var-etcd.automount
+      enable: true
+      contents: |
+        [Unit]
+        Wants=btrfs-create-subvolumes.service
+        After=DATA.mount
+        After=btrfs-create-subvolumes.service
+        Before=kubelet.service
+
+        [Automount]
+        Where=/var/etcd
+
+        [Install]
+        WantedBy=local-fs.target
+        WantedBy=kubelet.service
+    - name: etc-kubernetes.mount
+      enable: true
+      contents: |
+        [Unit]
+        Before=kubelet.service bootkube.service
+
+        [Mount]
+        What=/dev/disk/by-label/DATA
+        Where=/etc/kubernetes
+        Type=btrfs
+        Options=compress=lzo,subvol=/kubernetes
+    - name: etc-kubernetes.automount
+      enable: true
+      contents: |
+        [Unit]
+        Wants=btrfs-create-subvolumes.service
+        After=DATA.mount
+        After=btrfs-create-subvolumes.service
+        Before=kubelet.service bootkube.service
+
+        [Automount]
+        Where=/etc/kubernetes
+
+        [Install]
+        WantedBy=local-fs.target
+        WantedBy=kubelet.service bootkube.service
+    - name: home-core.mount
+      enable: true
+      contents: |
+        [Unit]
+        Before=coreos-metadata-sshkeys@core.service
+
+        [Mount]
+        What=/dev/disk/by-label/DATA
+        Where=/home/core
+        Type=btrfs
+        Options=compress=lzo,subvol=/core
+    - name: home-core.automount
+      enable: true
+      contents: |
+        [Unit]
+        Wants=btrfs-create-subvolumes.service
+        After=DATA.mount
+        After=btrfs-create-subvolumes.service
+        Before=coreos-metadata-sshkeys@core.service
+
+        [Automount]
+        Where=/home/core
+
+        [Install]
+        WantedBy=local-fs.target
+        WantedBy=coreos-metadata-sshkeys@core.service
 storage:
-  # links:
-  #   - path: /etc/resolv.conf
-  #     filesystem: root
-  #     target: /usr/lib/systemd/resolv.conf
-  #     user:
-  #       name: root
-  #     group:
-  #       name: root
-  #   - path: /etc/systemd/resolved.conf.d/50-no-dns-listener.conf
-  #     filesystem: root
-  #     target: /dev/null
-  #     user:
-  #       name: root
-  #     group:
-  #       name: root
+  disks:
+    # - device: /dev/sda
+    #   wipe_table: false
+    #   partitions:
+    #     # /var - 75GB
+    #     - number: 1
+    #       label: var
+    #       # size: 158118750
+    #       size: 75GB
+    #       start: 0
+    #     # /home - 25GB
+    #     - number: 2
+    #       label: home
+    #       # size: 52706250
+    #       size: 25GB
+    #       start: 0
+    #     # /etc - rest
+    #     - number: 3
+    #       label: etc
+    #       size: 0
+    #       start: 0
+  filesystems:
+    - name: data
+      mount:
+        device: /dev/sda
+        format: btrfs
+        create:
+          force: false
+          options:
+            - -L
+            - DATA
+    # - name: var
+    #   mount:
+    #     # device: /dev/sda1
+    #     device: /dev/disk/by-partlabel/var
+    #     format: btrfs
+    #     create:
+    #       force: false
+    #       options:
+    #         - -L
+    #         - VAR
+    # - name: home
+    #   mount:
+    #     # device: /dev/sda2
+    #     device: /dev/disk/by-partlabel/home
+    #     format: btrfs
+    #     create:
+    #       force: false
+    #       options:
+    #         - -L
+    #         - HOME
+    # - name: etc
+    #   mount
+    #     # device: /dev/sda3
+    #     device: /dev/disk/by-partlabel/etc
+    #     format: btrfs
+    #     create:
+    #       force: false
+    #       options:
+    #         - -L
+    #         - ETC
   files:
     - path: /etc/kubelet.env
       filesystem: root
@@ -142,6 +383,44 @@ storage:
       contents:
         inline: |
           fs.inotify.max_user_watches=16184
+    - path: /opt/bin/symlink-persistent-dirs.sh
+      filesystem: root
+      mode: 0544
+      contents:
+        inline: |
+          #!/usr/bin/env sh
+          set -xe
+
+          MOVE_DIR="/moved"
+          DATA_DIR="/DATA"
+
+          [ -n "$${PERSIST_DIRS}" ] || ( \
+              echo "Error: No PERSIST_DIRS provided"
+              exit 1)
+
+          mkdir -p "$${MOVE_DIR}"
+
+          for dir in $${PERSIST_DIRS}; do
+              DIR_NAME="$$(basename "$${dir}")"
+              DEST_DIR="$${MOVE_DIR}/$${DIR_NAME}"
+
+              if [ -d "$${dir}" ] && [ ! -L "$${dir}" ]
+              then
+                  if [ -d "$${DEST_DIR}" ]
+                  then
+                      cp -an "$${dir}"/* "$${DEST_DIR}"
+                  else
+                      mv "$${dir}" "$${DEST_DIR}"
+                  fi
+              else
+                  if [ -L "$${dir}" ]
+                  then
+                      continue
+                  else
+                      ln -s "$${DATA_DIR}/$${DIR_NAME}" "$${dir}"
+                  fi
+              fi
+          done
     - path: /opt/bootkube/bootkube-start
       filesystem: root
       mode: 0544
@@ -173,7 +452,7 @@ storage:
             --exec=/bootkube -- start --asset-dir=/assets "$@"
     - path: /etc/systemd/timesyncd.conf
       filesystem: root
-      mode: 0420
+      mode: 0620
       contents:
         inline: |
           [Time]
